# Generated by Django 4.2.3 on 2023-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reci_name', models.CharField(max_length=100)),
                ('reci_desc', models.TextField()),
                ('image', models.ImageField(upload_to='raw')),
            ],
        ),
    ]
