# Generated by Django 4.2.3 on 2023-08-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reci',
            old_name='reci_desc',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='reci',
            old_name='image',
            new_name='receipe_image',
        ),
        migrations.RenameField(
            model_name='reci',
            old_name='reci_name',
            new_name='receipe_name',
        ),
    ]
