# Generated by Django 4.2.3 on 2023-08-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_reci_desc_reci_receipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reci',
            name='receipe_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
