# Generated by Django 4.2.3 on 2023-09-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_reci_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reci',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
