# Generated by Django 4.2.3 on 2023-09-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_subjects_subjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
