# Generated by Django 4.2.3 on 2023-09-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_studentrank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentrank',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
