# Generated by Django 4.2.3 on 2023-09-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_alter_studentrank_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentrank',
            unique_together=set(),
        ),
    ]
