# Generated by Django 4.2.5 on 2023-09-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0015_reci_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reci',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
